### ISSUE TITLE
Some problems, please help!

### ISSUE THREAD

**Issue by metal-overlord** [Quzzar/Apeiron#6]
I'm sorry I had to write here, but I couldn't find a way to contact you otherwise.
Please can you help with your innovative mechanics plugin?
I and my friend want buy it but stupid paypal give errors...Paypal suport say:
**_this is most likely a user error.
If the user does not log in to the account for a long time, it is blocked, and it becomes impossible to make a payment._**
Please can you help with payment or give plugin?Please. 
.spigotmc.org/resources/◀-innovative-mechanics-▶-tech-mods-in-spigot-ic2-iron-chests.50654/

**Comment by Quzzar** [comment]
> I'm sorry I had to write here, but I couldn't find a way to contact you otherwise.
> Please can you help with your innovative mechanics plugin?
> I and my friend want buy it but stupid paypal give errors...Paypal suport say:
> **_this is most likely a user error. If the user does not log in to the account for a long time, it is blocked, and it becomes impossible to make a payment._**
> Please can you help with payment or give plugin?Please.
> .spigotmc.org/resources/◀-innovative-mechanics-▶-tech-mods-in-spigot-ic2-iron-chests.50654/

I haven't worked on that plugin for quite some time. I'm not sure it will even work in any of the newer versions. The fact that Paypal isn't letting you purchase it is probably for the better.
