### ISSUE TITLE
Dockerize WG

### ISSUE THREAD

**Issue by dsimonow** [Quzzar/Apeiron#9]
Currently looking into how to host WG.
This seems like a system that grown over the time with quite a lot of systems interacting.
What are the thoughts on a docker version of it? 
Were there attempts to dockerize it?

Could definitely help with the load surges people have in at primetime since its easier to manage as a container on a nas for example.
Especially for keeping it up to date.
I get that funnelling people to the main site and patreon helps the project the most.
Currently actually thinking about switching the whole group away from Wanderers Guide because of the increased load times and outtages although the project itself is great.

**Comment by Quzzar** [comment]
I have looked into dockerizing the project and it could help fix server overloads during prime hours. I just need to find the time to properly set it up.

I've made some changes with the database (which seems to be the primary issue) within the last couple days and am looking forward to this weekend to see if my changes resolved the overload problems.
If not, my plan is to make a dedicated effort to dockerize the project (which should greatly reduce the setup instructions as well haha).
Thanks for the feedback, appreciate it!
